#https://github.com/ruotianluo/pytorch-faster-rcnn
 
nvcc -c -o overlap_kernel.cu.o overlap_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_52

#/usr/local/cuda-9.1/bin/nvcc -c -o overlap_kernel.cu.o overlap_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_52


